language: python
dist: bionic
services:
- postgresql
python:
- '3.6'
- '3.8'
install:
- cd backend
- pip install -r requirements.txt
- python manage.py migrate
script:
- python manage.py test
env:
  global:
  - secure: dUBWGBCGbyljsOocl2gtWkX0L0H5TTLXD8P2sGsJwmPN0Dxq3gIH+KlWwZYD9I7FKKZWdTL4ssqbUpqN63l4TnucHm6imkY7L3ZE6FthlKcjC6KenoSgmOLX1XReJ7Jh8dAqMQLfJ/XTNRDLmyFBN00omxYlkq5U+DR7K61JOMYGqcp0EkeDF9x7twK7X45gx3xAWjJidPdFg9ZdraqRCghK5HrGu7PspjvuFdjJGRiRU+OZhDSp7v3p8aojde7L0vEcUL2WlOM2upAphUP/OsmeXpjwu6jIul9FbbKnbFoqZsJc8NbKG/SJVgyvI9ZY3Le8jNxWfyfVUu4lTUMXzoUqQdwbQ4HLAA2MZWypAodHhneeTUeMkGaxyQMkbF+DxPM1OSPf5575BLylXweda0uBMqhvpOtWeElXfqDt6xxEJ/Ns+tFfCoFb2itDkrLidM5mTqsAvbATSvRuRzAuVTCQPpY/Blylbt9k7n+oClDJYKIEoT8SJfbJDKy0O07fUvG8dTpCROf5zNvgeM/05DH1F9C3ZNlKDuxMVEq5NaP1DEClQScNgQpgWfT+lR5cuUHMiCuNW+l5XlayL3HbICZz6AUhjMQVWVKHGkJ6jSvutUvfahR9N1enh59ECcMDCZSgUf7RDugbY4tsZGrRhRVlV1sD7r28hRfBhyb+byM=
