# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlink',
            old_name='url',
            new_name='link_url',
        ),
    ]
