# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190529_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.CharField(max_length=64)),
                ('link_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='commentlink',
            name='comment',
        ),
        migrations.DeleteModel(
            name='CommentLink',
        ),
    ]
