# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20190529_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='play',
        ),
        migrations.RemoveField(
            model_name='link',
            name='play',
        ),
        migrations.AddField(
            model_name='comment',
            name='play_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='play_id',
            field=models.IntegerField(default=0),
        ),
    ]
