# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190529_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=2000),
        ),
    ]
